# Generated by Django 4.0.6 on 2022-07-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_type',
            new_name='employment_type',
        ),
        migrations.AlterField(
            model_name='employee',
            name='staff_number',
            field=models.CharField(max_length=15),
        ),
    ]
