# Generated by Django 4.0.6 on 2022-07-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_employee_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='passport_photo',
            field=models.ImageField(default='passport.jpg', upload_to='media/passport-photo/'),
        ),
    ]
