# Generated by Django 4.0.6 on 2022-07-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_employee_passport_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='passport_photo',
            field=models.ImageField(default='media/passport.jpg', upload_to='media/passport-photo/'),
        ),
    ]
